### PR TITLE
Change `profile group` to `profile`

### PR DESCRIPTION
**Pull request by audsc**
Partially addresses #65 .

### CODE REVIEW

**Comment by cdriehuys** [comment]
@audsc, Can you reopen this pull request against the develop branch?

**Comment by cdriehuys** [comment]
Cool thanks.

**Comment by audsc** [comment]
I still need to update the docs to reflect the change from

**Comment by audsc** [comment]
@cdriehuys  I think this commit should fix the tests. The files for the list and detail tests for profile and kmuser were off.

**Pull request merged**
